name: dotnet app

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: false
  
    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        context: .
        file: ./DemoProject/Dockerfile
        push: false